### ISSUE TITLE
文献or书籍界面缩放功能

### ISSUE THREAD

**Issue by ZhangRuiClaire** [Shaobin-Jiang/course-game#1]
现在阅读的那个pdf或者截图有点太大了，有点影响阅读

**Comment by Shaobin-Jiang** [comment]
应该不是很有必要做成那种可以交互式缩放的模式，如果说这个空间太大了，或许可以把它的宽度减小，目前的控件宽度占游戏可见区域宽度的`7 / 8`，高度占游戏可见区域高度的`2 / 3`：

```javascript
let reader: Reader = new Reader(
    level.paper,
    new Rect(this.width / 16, this.height / 6, (this.width * 7) / 8, (this.height * 2) / 3)
);
this.renderer.draw(reader);
```

游戏可见区域长宽比是`16 : 9`，所以最后得到的当前控件长宽比应该是`7 : 3`，或许可以把这个比例缩小到`2 : 1`？
