### ISSUE TITLE
【裂脑人】感觉手术刀用刀尖对着要切的地方比较合理...

### ISSUE THREAD

**Issue by Sihan-Sara** [Shaobin-Jiang/course-game#10]
虽然也能理解意图   但是用刀把切总感觉很奇怪）
![image](https://user-images.githubusercontent.com/124646031/217131842-07285fd3-b1e4-40fb-9bdc-1ff1d5f43a0d.png)

**Comment by Sihan-Sara** [comment]
还有第二关读文献必须要拉到最底下（但其实那一页只有左上角一点点有文献，下面都是空白的）

**Comment by Shaobin-Jiang** [comment]
> 虽然也能理解意图 但是用刀把切总感觉很奇怪） ![image](https://user-images.githubusercontent.com/124646031/217131842-07285fd3-b1e4-40fb-9bdc-1ff1d5f43a0d.png)

会意吧，这也算是致敬原作了2333

**Comment by Shaobin-Jiang** [comment]
> 还有第二关读文献必须要拉到最底下（但其实那一页只有左上角一点点有文献，下面都是空白的）

已更换图片
