### ISSUE TITLE
【心中的地图】显示问题

### ISSUE THREAD

**Issue by ZhangRuiClaire** [Shaobin-Jiang/course-game#12]
![图片](https://user-images.githubusercontent.com/124502687/217179310-07f049b9-e445-4916-94b0-3ed0ef376b11.png)
就是这里的提示方块，再次选择的时候，显示在了物体上方，如图

**Comment by ZhangRuiClaire** [comment]
【记忆】部分也有这个显示问题
拖动示威者的时候（这个问题真的太迷了），绿框时而在人的下面，时而在人的上面，然后有的时候部分在绿框上面，就有点点奇怪

**Comment by Shaobin-Jiang** [comment]
这是一个比较tricky的bug，我大概猜到它的问题出在哪里了。严格来说，这并不是一个bug，而真的是游戏引擎的一个feature，因为当前版本的游戏引擎会按照**控件的添加顺序渲染控件**，而拖拽目标区域的渲染是在拖拽控件本身的渲染过程中的。这就导致了先被添加的拖拽控件，其目标区域的渲染也先于后添加的拖拽控件，从而我们看到的就是这个区域时而出现在了物体的下方时而出现在了物体的上方。

**Comment by Shaobin-Jiang** [comment]
我能想到的解决方案是给`Drag`控件添加一个`static_draw`方法，这个方法只会把控件原原本本重绘一次而不检测交互。然后，我们在当前拖拽控件中，检测到目标区域下面有其他拖拽控件，就对它们进行静态的重绘。这样无论如何目标区域都会显示在所有控件下面。

**Comment by Shaobin-Jiang** [comment]
已修复 #17
