### ISSUE TITLE
【记忆】问题回答判定有问题

### ISSUE THREAD

**Issue by ZhangRuiClaire** [Shaobin-Jiang/course-game#14]
![图片](https://user-images.githubusercontent.com/124502687/217180769-637aa14b-a6ee-4704-823e-00ffb3ba112d.png)
答案是12或者4个示威者，这样子回答应该没有什么问题
![图片](https://user-images.githubusercontent.com/124502687/217180883-c041971c-fa68-4598-a0e6-1de67f04c21f.png)
但是必须要这样子回答才算正确，也就是说，交换位置的话就不对了
![图片](https://user-images.githubusercontent.com/124502687/217181102-ed9b40c5-54e1-4d99-b1df-f4211c46cbc3.png)

**Comment by Shaobin-Jiang** [comment]
已修复
