### ISSUE TITLE
【记忆】文字表述问题

### ISSUE THREAD

**Issue by ZhangRuiClaire** [Shaobin-Jiang/course-game#15]
![图片](https://user-images.githubusercontent.com/124502687/217181463-66cc3b4f-ca76-4bc6-94df-7cc63fabbdc3.png)

这个问题好长，后一个问题我要怎么做花了我好长的时间才明白要做什么才对。或许分个段会方便阅读理解一些

**Comment by Shaobin-Jiang** [comment]
已添加换行
