### ISSUE TITLE
【讨论】物品选择界面的文字呈现问题

### ISSUE THREAD

**Issue by ZhangRuiClaire** [Shaobin-Jiang/course-game#16]
刚才把下学期的游戏玩完啦，然后突然意识到了我在选择界面，开始只看加粗字体去进行选择了，其他的就干脆不看了
在想提示给的太明显之后，到底好还是不好
还是干脆不要这个页面也可以
有点没想清楚

**Comment by Shaobin-Jiang** [comment]
我的感觉是，这个可能更多是题目本身设计的问题，第一学期的题目很多即使看了加粗的提示文字，还是需要认真思考，而第二学期本身文本设计上就有太多那种 *选择全部物品* 这样的，所以要改可能还是应该对题目文本进行改善
