### ISSUE TITLE
新标签页角标的图像

### ISSUE THREAD

**Issue by ZhangRuiClaire** [Shaobin-Jiang/course-game#2]
![图片](https://user-images.githubusercontent.com/124502687/216819440-1c54398f-0eca-47f5-a72d-70c796f5a078.png)
想要标签页面上有角标可以实现吗✪ ω ✪
就是最左上角那里，可以参考像哔哩哔哩小电视那样子

**Comment by Shaobin-Jiang** [comment]
已添加
