### ISSUE TITLE
想想的图片好糊，可以换个高清一点的吗

### ISSUE THREAD

**Issue by ZhangRuiClaire** [Shaobin-Jiang/course-game#3]
![图片](https://user-images.githubusercontent.com/124502687/216819796-99ca5ba3-e6c2-4e25-9e6e-4e67fa165068.png)
以及抠图不是很完美，好像之前公众号是有高清的想想png空白底图片的？

**Comment by Shaobin-Jiang** [comment]
已于commit 88755238c4e496f2553612be87f8d3da7928d16b 中修改
