### ISSUE TITLE
【小阿尔伯特】题干字体太小了

### ISSUE THREAD

**Issue by ZhangRuiClaire** [Shaobin-Jiang/course-game#4]
![图片](https://user-images.githubusercontent.com/124502687/216820176-bdb840c5-c045-4a3e-9fbb-a7dd1df7da2d.png)
rt，有点影响阅读，实验流程那里，所有的题干都有些小，这里给了一个例子

**Comment by Shaobin-Jiang** [comment]
是有点小了，主要是考虑到有些问题文本很长，所以给这种长文本预留了空间。我再去检查一下有没有特别长的文本，然后可以看看调整字体大小或者干脆把这个对话框放大一些。

**Comment by Shaobin-Jiang** [comment]
@ZhangRuiClaire 可以看一下这个PR里的效果怎样 #7
