### ISSUE TITLE
【小阿尔伯特】游戏操作不顺滑问题，拖动图像方面的小问题

### ISSUE THREAD

**Issue by ZhangRuiClaire** [Shaobin-Jiang/course-game#5]
![图片](https://user-images.githubusercontent.com/124502687/216820367-2204451a-92c2-4200-bc9e-16e0588b77f6.png)
就是在拖动右边的图像之前，需要点一下，让想想消失才可以拖动
第一遍拖动的时候不知道，鼠标按下去之后怎么拖都没拖动，松开之后第二遍才成功

**Comment by Shaobin-Jiang** [comment]
这个是这样设计的。因为控件的设计有一个`freeze`状态，将这个状态设置为`true`后渲染器就只会对它渲染一次，这样可以优化性能。所以，这个状态在一次`render`中是不可变的。为了防止玩家在呈现问题期间就去和控件交互，这个时候所有的控件的`freeze`都被设置为了`true`，而在玩家点击屏幕后，引擎会对画面进行一次重绘，再将需要交互的控件的`freeze`设置为`false`。

然后，控件监听鼠标点击走的不完全是JavaScript的`click`事件，而是在渲染器监听到`click`事件后把交互信息转发给控件，这个转发是每帧做一次的，而鼠标点击屏幕那一帧的时候引擎还没有对画面进行重绘，所以这个设计模式很难实现鼠标按下后同时完成问题消失 + 开始交互的功能。
