### ISSUE TITLE
“HOME”键

### ISSUE THREAD

**Issue by ZhangRuiClaire** [Shaobin-Jiang/course-game#6]
因为Home界面有些混乱，所以在选择第二个章节的时候不小心误选成了第一章（；´д｀）ゞ
但是想要返回最开始，重新选择第二章，需要完全退出整个网页才能再进去，好不方便的说

**Comment by Shaobin-Jiang** [comment]
游戏里有内置菜单，可以按<kbd>esc</kbd>呼出菜单，然后从那里回退到选择章节的界面。
