### ISSUE TITLE
【敲敲木头】字体大小问题

### ISSUE THREAD

**Issue by ZhangRuiClaire** [Shaobin-Jiang/course-game#8]
![图片](https://user-images.githubusercontent.com/124502687/216923686-ecef309b-87c8-42bd-ab4a-1f9e8197e0a5.png)
图片是字体大小不均，以及普遍偏小的问题，会增加阅读困难

**Comment by ZhangRuiClaire** [comment]
![图片](https://user-images.githubusercontent.com/124502687/216925593-d54ddeca-76e9-49b2-b222-137b86a3e566.png)
这里”跳舞的鸽子“等下方小字都看不太清
或许换成白色然后放大字号会好一些？因为底是棕色所以黑色不明显

**Comment by ZhangRuiClaire** [comment]
![图片](https://user-images.githubusercontent.com/124502687/216925593-d54ddeca-76e9-49b2-b222-137b86a3e566.png)
这里”跳舞的鸽子“等下方小字都看不太清

**Comment by ZhangRuiClaire** [comment]
![图片](https://user-images.githubusercontent.com/124502687/216925842-29046096-e390-49ac-80c5-85d429ec0c4e.png)
这里的想想的题干也有点小，是还没来得及调整吗？

**Comment by Shaobin-Jiang** [comment]
已修复
