### ISSUE TITLE
【罗森塔尔】想想问题文字大小

### ISSUE THREAD

**Issue by ZhangRuiClaire** [Shaobin-Jiang/course-game#9]
![图片](https://user-images.githubusercontent.com/124502687/216928783-96e6694a-ee70-48e1-a5fa-a553d985d316.png)
感觉这一章文字也好多哦，也挺小的，需要凑近去看

**Comment by Shaobin-Jiang** [comment]
这个已经改了，但是后端还没部署，因为还有几个地方要改，改完之后一起更新。
